/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/views/About.vue')['default']
    Home: typeof import('./src/components/views/Home.vue')['default']
    IngredientDetails: typeof import('./src/components/views/IngredientDetails.vue')['default']
    Ingredients: typeof import('./src/components/views/Ingredients.vue')['default']
    RecipeDetails: typeof import('./src/components/views/RecipeDetails.vue')['default']
    Recipes: typeof import('./src/components/views/Recipes.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SideBar: typeof import('./src/components/navigation/SideBar.vue')['default']
    TopBar: typeof import('./src/components/navigation/TopBar.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFooter: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPageHero: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
  }
}

// For TSX support
declare global {
  const About: typeof import('./src/components/views/About.vue')['default']
  const Home: typeof import('./src/components/views/Home.vue')['default']
  const IngredientDetails: typeof import('./src/components/views/IngredientDetails.vue')['default']
  const Ingredients: typeof import('./src/components/views/Ingredients.vue')['default']
  const RecipeDetails: typeof import('./src/components/views/RecipeDetails.vue')['default']
  const Recipes: typeof import('./src/components/views/Recipes.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const SideBar: typeof import('./src/components/navigation/SideBar.vue')['default']
  const TopBar: typeof import('./src/components/navigation/TopBar.vue')['default']
  const UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
  const UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  const UFooter: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
  const UHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
  const UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
  const UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  const UPageHero: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
}