/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    About: typeof import('./src/components/views/AboutPage.vue')['default']
    AboutPage: typeof import('./src/components/views/AboutPage.vue')['default']
    Home: typeof import('./src/components/views/HomePage.vue')['default']
    HomePage: typeof import('./src/components/views/HomePage.vue')['default']
    IngredientDetails: typeof import('./src/components/views/IngredientDetails.vue')['default']
    Ingredients: typeof import('./src/components/views/IngredientsPage.vue')['default']
    IngredientsPage: typeof import('./src/components/views/IngredientsPage.vue')['default']
    RecipeDetails: typeof import('./src/components/views/RecipeDetails.vue')['default']
    Recipes: typeof import('./src/components/views/RecipesPage.vue')['default']
    RecipesPage: typeof import('./src/components/views/RecipesPage.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TopBar: typeof import('./src/components/navigation/TopBar.vue')['default']
    UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
    UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
    UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
    UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
    UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
    UFooter: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
    UHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
    UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
    UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
    UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
    UPage: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
    UPageBody: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue')['default']
    UPageCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
    UPageGrid: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
    UPageHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
    UPageHero: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
    UPageSection: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue')['default']
    UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
    UUser: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/User.vue')['default']
  }
}

// For TSX support
declare global {
  const About: typeof import('./src/components/views/AboutPage.vue')['default']
  const AboutPage: typeof import('./src/components/views/AboutPage.vue')['default']
  const Home: typeof import('./src/components/views/HomePage.vue')['default']
  const HomePage: typeof import('./src/components/views/HomePage.vue')['default']
  const IngredientDetails: typeof import('./src/components/views/IngredientDetails.vue')['default']
  const Ingredients: typeof import('./src/components/views/IngredientsPage.vue')['default']
  const IngredientsPage: typeof import('./src/components/views/IngredientsPage.vue')['default']
  const RecipeDetails: typeof import('./src/components/views/RecipeDetails.vue')['default']
  const Recipes: typeof import('./src/components/views/RecipesPage.vue')['default']
  const RecipesPage: typeof import('./src/components/views/RecipesPage.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const TopBar: typeof import('./src/components/navigation/TopBar.vue')['default']
  const UApp: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/App.vue')['default']
  const UBadge: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Badge.vue')['default']
  const UButton: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Button.vue')['default']
  const UCarousel: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Carousel.vue')['default']
  const UContainer: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Container.vue')['default']
  const UFooter: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Footer.vue')['default']
  const UHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Header.vue')['default']
  const UInput: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Input.vue')['default']
  const UMain: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Main.vue')['default']
  const UNavigationMenu: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/NavigationMenu.vue')['default']
  const UPage: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Page.vue')['default']
  const UPageBody: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageBody.vue')['default']
  const UPageCard: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageCard.vue')['default']
  const UPageGrid: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageGrid.vue')['default']
  const UPageHeader: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHeader.vue')['default']
  const UPageHero: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageHero.vue')['default']
  const UPageSection: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/PageSection.vue')['default']
  const UProgress: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/Progress.vue')['default']
  const UUser: typeof import('./node_modules/@nuxt/ui/dist/runtime/components/User.vue')['default']
}